# Test find_adjacent_tiles
    # print(board.get_adjacent_tiles(0, 0))
    # print(board.get_adjacent_tiles(0, 4))
    # print(board.get_adjacent_tiles(4, 0))
    # print(board.get_adjacent_tiles(4, 4))
    # print(board.get_adjacent_tiles(0, 2))
    # print(board.get_adjacent_tiles(2, 0))
    # print(board.get_adjacent_tiles(4, 2))
    # print(board.get_adjacent_tiles(2, 4))
    # print(board.get_adjacent_tiles(2, 2))
    #
    # # Test Flip Tile
    # board.flip_tile(0, 0)
    # board.flip_tile(0, 4)
    # board.flip_tile(4, 0)
    # board.flip_tile(4, 4)
    # board.flip_tile(0, 2)
    # board.flip_tile(2, 0)
    # board.flip_tile(4, 2)
    # board.flip_tile(2, 4)
    # board.flip_tile(2, 2)